//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubmissionsTracker
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Submission
    {
        public short Id { get; set; }
        public System.DateTime DateSubmitted { get; set; }
        public string Reply { get; set; }
        public string Company { get; set; }
        public string Position { get; set; }
        public string ContactPerson { get; set; }
        public string Location { get; set; }
        public string JobBoard { get; set; }
        public string JobBoardId { get; set; }
        public string SubmittedThrough { get; set; }
        public string ListingWebAddress { get; set; }
        public string CompanyWebAddress { get; set; }
        public string Notes { get; set; }
    }
}
